// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: src/main/java/org/jetbrains/plugins/template/ui/lexer/Ui.flex

package org.jetbrains.plugins.template.ui.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import org.jetbrains.plugins.template.ui.psi.UiTypes;
import com.intellij.psi.TokenType;


class UiLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\0\1\6\1\7\1\10\3\0\1\11\1\12\1\13"+
    "\1\0\1\14\1\0\1\15\1\16\12\17\1\20\1\21"+
    "\1\0\1\22\2\0\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\3\34\1\35\1\36\1\37"+
    "\1\34\1\40\1\34\1\41\1\42\1\43\1\34\1\44"+
    "\1\45\3\34\1\46\1\47\1\50\1\0\1\34\1\0"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\34\1\62\1\63\1\64\1\65\1\66\1\67"+
    "\1\34\1\70\1\71\1\72\1\73\1\34\1\74\1\75"+
    "\1\76\1\77\1\100\1\0\1\101\7\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\1\12\1\13\1\14\1\15"+
    "\21\16\1\17\1\20\2\16\1\21\1\22\1\0\1\23"+
    "\4\0\1\24\1\0\37\16\1\0\1\25\2\0\1\11"+
    "\33\16\1\26\5\16\2\0\1\24\15\16\1\26\12\16"+
    "\1\27\3\16\1\30\1\0\14\16\1\31\7\16\1\27"+
    "\5\16\1\0\22\16\1\32\20\16\1\0\14\16\1\0"+
    "\10\16\1\32\7\16\1\33\4\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[246];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\102\0\204\0\306\0\u0108\0\102\0\102\0\102"+
    "\0\102\0\u014a\0\u018c\0\u01ce\0\102\0\102\0\102\0\102"+
    "\0\u0210\0\u0252\0\u0294\0\u02d6\0\u0318\0\u035a\0\u039c\0\u03de"+
    "\0\u0420\0\u0462\0\u04a4\0\u04e6\0\u0528\0\u056a\0\u05ac\0\u05ee"+
    "\0\u0630\0\102\0\102\0\u0672\0\u06b4\0\102\0\102\0\306"+
    "\0\102\0\u06f6\0\u0738\0\u077a\0\u07bc\0\u07fe\0\u0840\0\u0882"+
    "\0\u08c4\0\u0906\0\u0948\0\u098a\0\u09cc\0\u0a0e\0\u0a50\0\u0a92"+
    "\0\u0ad4\0\u0b16\0\u0b58\0\u0b9a\0\u0bdc\0\u0c1e\0\u0c60\0\u0ca2"+
    "\0\u0ce4\0\u0d26\0\u0d68\0\u0daa\0\u0dec\0\u0e2e\0\u0e70\0\u0eb2"+
    "\0\u0ef4\0\u0f36\0\u0f78\0\u0fba\0\u0ffc\0\u103e\0\u1080\0\102"+
    "\0\u10c2\0\u1104\0\u0840\0\u1146\0\u1188\0\u11ca\0\u120c\0\u124e"+
    "\0\u1290\0\u12d2\0\u1314\0\u1356\0\u1398\0\u13da\0\u141c\0\u145e"+
    "\0\u14a0\0\u14e2\0\u1524\0\u1566\0\u15a8\0\u15ea\0\u162c\0\u166e"+
    "\0\u16b0\0\u16f2\0\u1734\0\u1776\0\u17b8\0\u17fa\0\u183c\0\u187e"+
    "\0\u18c0\0\u1902\0\u1944\0\u1986\0\u19c8\0\u1a0a\0\102\0\u1a4c"+
    "\0\u1a8e\0\u1ad0\0\u1b12\0\u1b54\0\u1b96\0\u1bd8\0\u1c1a\0\u1c5c"+
    "\0\u1c9e\0\u1ce0\0\u1d22\0\u1d64\0\u0318\0\u1da6\0\u1de8\0\u1e2a"+
    "\0\u1e6c\0\u1eae\0\u1ef0\0\u1f32\0\u1f74\0\u1fb6\0\u1ff8\0\u203a"+
    "\0\u207c\0\u20be\0\u2100\0\u0318\0\u2142\0\u2184\0\u21c6\0\u2208"+
    "\0\u224a\0\u228c\0\u22ce\0\u2310\0\u2352\0\u2394\0\u23d6\0\u2418"+
    "\0\u245a\0\u0318\0\u249c\0\u24de\0\u2520\0\u2562\0\u25a4\0\u25e6"+
    "\0\u2628\0\u0318\0\u266a\0\u26ac\0\u26ee\0\u2730\0\u2772\0\u27b4"+
    "\0\u27f6\0\u2838\0\u287a\0\u28bc\0\u28fe\0\u2940\0\u2982\0\u29c4"+
    "\0\u2a06\0\u2a48\0\u2a8a\0\u2acc\0\u2b0e\0\u2b50\0\u2b92\0\u2bd4"+
    "\0\u2c16\0\u2c58\0\u2c9a\0\u2cdc\0\u2d1e\0\u2d60\0\u2da2\0\u2de4"+
    "\0\u2e26\0\u2e68\0\u2eaa\0\u2eec\0\u2f2e\0\u2f70\0\u2fb2\0\u2ff4"+
    "\0\u3036\0\u3078\0\u30ba\0\u30fc\0\u313e\0\u3180\0\u31c2\0\u3204"+
    "\0\u3246\0\u3288\0\u32ca\0\u330c\0\u334e\0\u3390\0\u33d2\0\u3414"+
    "\0\u3456\0\u3498\0\u34da\0\u351c\0\u355e\0\u35a0\0\u35e2\0\u3624"+
    "\0\u3666\0\102\0\u36a8\0\u36ea\0\u372c\0\u376e\0\u37b0\0\u37f2"+
    "\0\u3834\0\u0318\0\u3876\0\u38b8\0\u38fa\0\u393c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[246];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\2\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\25\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\2\1\43"+
    "\5\25\1\44\13\25\1\45\5\25\1\46\1\47\103\0"+
    "\2\3\1\0\1\3\75\0\2\50\1\0\2\50\1\0"+
    "\1\51\40\50\1\52\32\50\17\0\1\53\4\0\6\53"+
    "\17\0\6\53\40\0\1\54\77\0\1\55\2\0\1\56"+
    "\100\0\1\57\1\0\1\14\101\0\1\25\4\0\22\25"+
    "\3\0\14\25\1\60\12\25\21\0\1\25\4\0\22\25"+
    "\3\0\1\61\14\25\1\62\4\25\1\63\4\25\21\0"+
    "\1\25\4\0\22\25\3\0\4\25\1\64\2\25\1\65"+
    "\5\25\1\66\11\25\21\0\1\25\4\0\22\25\3\0"+
    "\17\25\1\67\7\25\21\0\1\25\4\0\22\25\3\0"+
    "\27\25\21\0\1\25\4\0\22\25\3\0\10\25\1\70"+
    "\1\25\1\71\2\25\1\72\4\25\1\73\4\25\21\0"+
    "\1\25\4\0\22\25\3\0\17\25\1\74\7\25\21\0"+
    "\1\25\4\0\22\25\3\0\4\25\1\75\22\25\21\0"+
    "\1\25\4\0\22\25\3\0\1\76\3\25\1\77\22\25"+
    "\21\0\1\25\4\0\22\25\3\0\1\100\26\25\21\0"+
    "\1\25\4\0\22\25\3\0\22\25\1\101\4\25\21\0"+
    "\1\25\4\0\22\25\3\0\1\102\26\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\103\3\25\1\104\16\25"+
    "\21\0\1\25\4\0\22\25\3\0\2\25\1\105\13\25"+
    "\1\106\2\25\1\107\5\25\21\0\1\25\4\0\22\25"+
    "\3\0\4\25\1\110\10\25\1\111\11\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\112\22\25\21\0\1\25"+
    "\4\0\22\25\3\0\10\25\1\113\6\25\1\114\7\25"+
    "\21\0\1\25\4\0\22\25\3\0\1\115\26\25\21\0"+
    "\1\25\4\0\22\25\3\0\17\25\1\116\7\25\2\0"+
    "\2\50\4\0\74\50\17\0\1\117\4\0\6\117\17\0"+
    "\6\117\40\0\1\120\64\0\13\121\1\122\66\121\2\56"+
    "\1\0\2\56\1\0\74\56\17\0\1\123\101\0\1\25"+
    "\4\0\22\25\3\0\2\25\1\124\24\25\21\0\1\25"+
    "\4\0\22\25\3\0\2\25\1\125\24\25\21\0\1\25"+
    "\4\0\22\25\3\0\17\25\1\126\1\25\1\127\5\25"+
    "\21\0\1\25\4\0\22\25\3\0\21\25\1\130\5\25"+
    "\21\0\1\25\4\0\22\25\3\0\14\25\1\131\12\25"+
    "\21\0\1\25\4\0\22\25\3\0\4\25\1\132\22\25"+
    "\21\0\1\25\4\0\22\25\3\0\12\25\1\133\1\134"+
    "\13\25\21\0\1\25\4\0\22\25\3\0\15\25\1\135"+
    "\11\25\21\0\1\25\4\0\22\25\3\0\12\25\1\136"+
    "\14\25\21\0\1\25\4\0\22\25\3\0\4\25\1\137"+
    "\22\25\21\0\1\25\4\0\22\25\3\0\14\25\1\140"+
    "\12\25\21\0\1\25\4\0\22\25\3\0\12\25\1\141"+
    "\14\25\21\0\1\25\4\0\22\25\3\0\15\25\1\142"+
    "\11\25\21\0\1\25\4\0\22\25\3\0\10\25\1\104"+
    "\16\25\21\0\1\25\4\0\22\25\3\0\1\25\1\143"+
    "\23\25\1\144\1\25\21\0\1\25\4\0\22\25\3\0"+
    "\5\25\1\145\21\25\21\0\1\25\4\0\22\25\3\0"+
    "\24\25\1\146\2\25\21\0\1\25\4\0\22\25\3\0"+
    "\13\25\1\147\13\25\21\0\1\25\4\0\22\25\3\0"+
    "\3\25\1\150\10\25\1\143\12\25\21\0\1\25\4\0"+
    "\22\25\3\0\14\25\1\151\12\25\21\0\1\25\4\0"+
    "\22\25\3\0\6\25\1\152\20\25\21\0\1\25\4\0"+
    "\22\25\3\0\17\25\1\153\7\25\21\0\1\25\4\0"+
    "\22\25\3\0\17\25\1\154\7\25\21\0\1\25\4\0"+
    "\22\25\3\0\25\25\1\155\1\25\21\0\1\25\4\0"+
    "\22\25\3\0\24\25\1\156\2\25\21\0\1\25\4\0"+
    "\22\25\3\0\16\25\1\157\10\25\21\0\1\25\4\0"+
    "\22\25\3\0\17\25\1\160\7\25\21\0\1\25\4\0"+
    "\22\25\3\0\3\25\1\161\23\25\21\0\1\25\4\0"+
    "\22\25\3\0\1\162\26\25\21\0\1\25\4\0\22\25"+
    "\3\0\12\25\1\163\14\25\21\0\1\25\4\0\22\25"+
    "\3\0\22\25\1\164\4\25\21\0\1\165\4\0\6\165"+
    "\17\0\6\165\23\0\13\121\1\166\66\121\13\0\1\122"+
    "\2\0\1\167\102\0\1\25\4\0\22\25\3\0\7\25"+
    "\1\170\17\25\21\0\1\25\4\0\22\25\3\0\11\25"+
    "\1\171\15\25\21\0\1\25\4\0\22\25\3\0\3\25"+
    "\1\172\23\25\21\0\1\25\4\0\22\25\3\0\21\25"+
    "\1\173\5\25\21\0\1\25\4\0\22\25\3\0\21\25"+
    "\1\174\5\25\21\0\1\25\4\0\22\25\3\0\21\25"+
    "\1\175\5\25\21\0\1\25\4\0\22\25\3\0\2\25"+
    "\1\176\24\25\21\0\1\25\4\0\22\25\3\0\15\25"+
    "\1\177\11\25\21\0\1\25\4\0\22\25\3\0\16\25"+
    "\1\200\10\25\21\0\1\25\4\0\22\25\3\0\16\25"+
    "\1\201\10\25\21\0\1\25\4\0\22\25\3\0\4\25"+
    "\1\202\22\25\21\0\1\25\4\0\22\25\3\0\24\25"+
    "\1\203\2\25\21\0\1\25\4\0\22\25\3\0\21\25"+
    "\1\204\5\25\21\0\1\25\4\0\22\25\3\0\12\25"+
    "\1\205\14\25\21\0\1\25\4\0\22\25\3\0\22\25"+
    "\1\206\4\25\21\0\1\25\4\0\22\25\3\0\4\25"+
    "\1\207\22\25\21\0\1\25\4\0\22\25\3\0\15\25"+
    "\1\210\11\25\21\0\1\25\4\0\22\25\3\0\21\25"+
    "\1\205\5\25\21\0\1\25\4\0\11\25\1\211\10\25"+
    "\3\0\27\25\21\0\1\25\4\0\22\25\3\0\1\25"+
    "\1\212\25\25\21\0\1\25\4\0\22\25\3\0\3\25"+
    "\1\213\23\25\21\0\1\25\4\0\22\25\3\0\3\25"+
    "\1\214\23\25\21\0\1\25\4\0\22\25\3\0\7\25"+
    "\1\145\17\25\21\0\1\25\4\0\22\25\3\0\15\25"+
    "\1\215\11\25\21\0\1\25\4\0\22\25\3\0\10\25"+
    "\1\216\16\25\21\0\1\25\4\0\22\25\3\0\12\25"+
    "\1\217\14\25\21\0\1\25\4\0\22\25\3\0\21\25"+
    "\1\220\5\25\21\0\1\25\4\0\16\25\1\221\3\25"+
    "\3\0\27\25\21\0\1\25\4\0\22\25\3\0\21\25"+
    "\1\222\5\25\21\0\1\25\4\0\22\25\3\0\21\25"+
    "\1\223\5\25\21\0\1\25\4\0\22\25\3\0\16\25"+
    "\1\205\10\25\21\0\1\25\4\0\22\25\3\0\20\25"+
    "\1\164\6\25\21\0\1\25\4\0\22\25\3\0\4\25"+
    "\1\224\22\25\21\0\1\225\4\0\6\225\17\0\6\225"+
    "\23\0\13\121\1\166\2\121\1\167\63\121\17\0\1\25"+
    "\4\0\22\25\3\0\15\25\1\226\11\25\21\0\1\25"+
    "\4\0\1\25\1\227\20\25\3\0\6\25\1\230\20\25"+
    "\21\0\1\25\4\0\22\25\3\0\4\25\1\226\22\25"+
    "\21\0\1\25\4\0\22\25\3\0\15\25\1\231\11\25"+
    "\21\0\1\25\4\0\22\25\3\0\15\25\1\232\11\25"+
    "\21\0\1\25\4\0\22\25\3\0\4\25\1\233\22\25"+
    "\21\0\1\25\4\0\22\25\3\0\11\25\1\234\15\25"+
    "\21\0\1\25\4\0\22\25\3\0\17\25\1\235\7\25"+
    "\21\0\1\25\4\0\22\25\3\0\1\236\26\25\21\0"+
    "\1\25\4\0\22\25\3\0\3\25\1\237\23\25\21\0"+
    "\1\25\4\0\3\25\1\24\16\25\3\0\27\25\21\0"+
    "\1\25\4\0\21\25\1\240\3\0\27\25\21\0\1\25"+
    "\4\0\16\25\1\241\3\25\3\0\27\25\21\0\1\25"+
    "\4\0\22\25\3\0\16\25\1\242\10\25\21\0\1\25"+
    "\4\0\22\25\3\0\12\25\1\242\14\25\21\0\1\25"+
    "\4\0\22\25\3\0\22\25\1\243\4\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\244\22\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\245\22\25\21\0\1\25"+
    "\4\0\22\25\3\0\10\25\1\246\16\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\247\22\25\21\0\1\25"+
    "\4\0\22\25\3\0\12\25\1\250\14\25\21\0\1\25"+
    "\4\0\22\25\3\0\21\25\1\251\5\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\252\22\25\21\0\1\25"+
    "\4\0\1\25\1\227\1\253\2\25\1\254\14\25\3\0"+
    "\22\25\1\255\4\25\21\0\1\25\4\0\22\25\3\0"+
    "\2\25\1\256\24\25\21\0\1\25\4\0\22\25\3\0"+
    "\10\25\1\257\16\25\21\0\1\25\4\0\22\25\3\0"+
    "\7\25\1\205\17\25\21\0\1\260\4\0\6\260\17\0"+
    "\6\260\42\0\1\25\4\0\22\25\3\0\17\25\1\252"+
    "\7\25\21\0\1\25\4\0\22\25\3\0\22\25\1\63"+
    "\4\25\21\0\1\25\4\0\22\25\3\0\17\25\1\261"+
    "\7\25\21\0\1\25\4\0\22\25\3\0\13\25\1\205"+
    "\13\25\21\0\1\25\4\0\22\25\3\0\14\25\1\242"+
    "\12\25\21\0\1\25\4\0\22\25\3\0\17\25\1\205"+
    "\7\25\21\0\1\25\4\0\1\25\1\262\20\25\3\0"+
    "\27\25\21\0\1\25\4\0\14\25\1\263\5\25\3\0"+
    "\27\25\21\0\1\25\4\0\22\25\3\0\2\25\1\264"+
    "\24\25\21\0\1\25\4\0\22\25\3\0\15\25\1\265"+
    "\11\25\21\0\1\25\4\0\22\25\3\0\4\25\1\266"+
    "\22\25\21\0\1\25\4\0\22\25\3\0\10\25\1\267"+
    "\16\25\21\0\1\25\4\0\22\25\3\0\21\25\1\270"+
    "\5\25\21\0\1\25\4\0\22\25\3\0\14\25\1\271"+
    "\12\25\21\0\1\25\4\0\22\25\3\0\17\25\1\272"+
    "\7\25\21\0\1\25\4\0\22\25\3\0\14\25\1\273"+
    "\12\25\21\0\1\25\4\0\22\25\3\0\17\25\1\274"+
    "\7\25\21\0\1\25\4\0\22\25\3\0\12\25\1\275"+
    "\14\25\21\0\1\25\4\0\22\25\3\0\4\25\1\242"+
    "\22\25\21\0\1\25\4\0\22\25\3\0\15\25\1\276"+
    "\11\25\21\0\1\25\4\0\22\25\3\0\10\25\1\277"+
    "\16\25\21\0\1\25\4\0\22\25\3\0\17\25\1\300"+
    "\7\25\21\0\1\25\4\0\22\25\3\0\17\25\1\301"+
    "\7\25\21\0\1\25\4\0\22\25\3\0\2\25\1\302"+
    "\24\25\21\0\1\303\4\0\6\303\17\0\6\303\42\0"+
    "\1\25\4\0\22\25\3\0\15\25\1\304\11\25\21\0"+
    "\1\25\4\0\22\25\3\0\15\25\1\305\11\25\21\0"+
    "\1\25\4\0\22\25\3\0\10\25\1\306\16\25\21\0"+
    "\1\25\4\0\22\25\3\0\21\25\1\307\5\25\21\0"+
    "\1\25\4\0\22\25\3\0\23\25\1\310\3\25\21\0"+
    "\1\25\4\0\22\25\3\0\10\25\1\311\16\25\21\0"+
    "\1\25\4\0\22\25\3\0\26\25\1\312\21\0\1\25"+
    "\4\0\12\25\1\313\7\25\3\0\27\25\21\0\1\25"+
    "\4\0\22\25\3\0\6\25\1\314\20\25\21\0\1\25"+
    "\4\0\5\25\1\254\14\25\3\0\27\25\21\0\1\25"+
    "\4\0\22\25\3\0\6\25\1\252\20\25\21\0\1\25"+
    "\4\0\1\25\1\315\20\25\3\0\27\25\21\0\1\25"+
    "\4\0\22\25\3\0\1\25\1\316\25\25\21\0\1\25"+
    "\4\0\22\25\3\0\12\25\1\317\14\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\320\22\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\321\22\25\21\0\1\25"+
    "\4\0\22\25\3\0\15\25\1\322\11\25\21\0\1\25"+
    "\4\0\22\25\3\0\1\323\26\25\13\0\1\324\107\0"+
    "\1\25\4\0\22\25\3\0\22\25\1\325\4\25\21\0"+
    "\1\25\4\0\22\25\3\0\24\25\1\242\2\25\21\0"+
    "\1\25\4\0\22\25\3\0\2\25\1\326\24\25\21\0"+
    "\1\25\4\0\17\25\1\327\2\25\3\0\27\25\21\0"+
    "\1\25\4\0\22\25\3\0\14\25\1\234\12\25\21\0"+
    "\1\25\4\0\22\25\3\0\6\25\1\330\20\25\21\0"+
    "\1\25\4\0\22\25\3\0\4\25\1\205\22\25\21\0"+
    "\1\25\4\0\22\25\3\0\15\25\1\331\11\25\21\0"+
    "\1\25\4\0\22\25\3\0\21\25\1\332\5\25\21\0"+
    "\1\25\4\0\22\25\3\0\15\25\1\333\11\25\21\0"+
    "\1\25\4\0\22\25\3\0\1\334\26\25\21\0\1\25"+
    "\4\0\22\25\3\0\15\25\1\233\11\25\21\0\1\25"+
    "\4\0\22\25\3\0\12\25\1\335\14\25\21\0\1\25"+
    "\4\0\14\25\1\336\5\25\3\0\27\25\21\0\1\25"+
    "\4\0\22\25\3\0\12\25\1\337\14\25\21\0\1\25"+
    "\4\0\22\25\3\0\12\25\1\340\14\25\17\0\1\341"+
    "\1\0\1\341\101\0\1\25\4\0\22\25\3\0\14\25"+
    "\1\342\12\25\21\0\1\25\4\0\22\25\3\0\11\25"+
    "\1\343\15\25\21\0\1\25\4\0\22\25\3\0\4\25"+
    "\1\344\22\25\21\0\1\25\4\0\22\25\3\0\7\25"+
    "\1\345\17\25\21\0\1\25\4\0\22\25\3\0\3\25"+
    "\1\217\23\25\21\0\1\25\4\0\22\25\3\0\7\25"+
    "\1\252\17\25\21\0\1\25\4\0\22\25\3\0\12\25"+
    "\1\346\14\25\21\0\1\25\4\0\22\25\3\0\17\25"+
    "\1\347\7\25\21\0\1\25\4\0\22\25\3\0\3\25"+
    "\1\242\23\25\21\0\1\25\4\0\22\25\3\0\1\314"+
    "\26\25\21\0\1\25\4\0\22\25\3\0\12\25\1\350"+
    "\14\25\21\0\1\25\4\0\1\351\21\25\3\0\27\25"+
    "\14\0\1\352\2\0\1\341\1\0\1\341\101\0\1\25"+
    "\4\0\22\25\3\0\3\25\1\252\23\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\353\22\25\21\0\1\25"+
    "\4\0\22\25\3\0\24\25\1\354\2\25\21\0\1\25"+
    "\4\0\22\25\3\0\21\25\1\252\5\25\21\0\1\25"+
    "\4\0\22\25\3\0\3\25\1\205\23\25\21\0\1\25"+
    "\4\0\16\25\1\355\3\25\3\0\27\25\21\0\1\25"+
    "\4\0\22\25\3\0\10\25\1\356\16\25\21\0\1\25"+
    "\4\0\22\25\3\0\12\25\1\357\14\25\21\0\1\25"+
    "\4\0\22\25\3\0\17\25\1\202\7\25\21\0\1\25"+
    "\4\0\22\25\3\0\21\25\1\272\5\25\21\0\1\25"+
    "\4\0\22\25\3\0\21\25\1\107\5\25\21\0\1\25"+
    "\4\0\22\25\3\0\14\25\1\360\12\25\21\0\1\25"+
    "\4\0\22\25\3\0\10\25\1\361\16\25\21\0\1\25"+
    "\4\0\22\25\3\0\6\25\1\362\20\25\21\0\1\25"+
    "\4\0\22\25\3\0\6\25\1\363\20\25\21\0\1\25"+
    "\4\0\22\25\3\0\14\25\1\364\12\25\21\0\1\25"+
    "\4\0\22\25\3\0\13\25\1\365\13\25\21\0\1\25"+
    "\4\0\22\25\3\0\4\25\1\366\22\25\21\0\1\25"+
    "\4\0\22\25\3\0\14\25\1\145\12\25\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[14718];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\4\11\3\1\4\11\21\1\2\11"+
    "\2\1\2\11\1\0\1\11\4\0\1\1\1\0\37\1"+
    "\1\0\1\11\2\0\42\1\2\0\1\11\35\1\1\0"+
    "\32\1\1\0\43\1\1\0\14\1\1\0\10\1\1\11"+
    "\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[246];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  UiLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return TokenType.BAD_CHARACTER;
            }
          // fall through
          case 28: break;
          case 2:
            { return TokenType.WHITE_SPACE;
            }
          // fall through
          case 29: break;
          case 3:
            { return UiTypes.HASH;
            }
          // fall through
          case 30: break;
          case 4:
            { return UiTypes.DOLLAR;
            }
          // fall through
          case 31: break;
          case 5:
            { return UiTypes.LPAREN;
            }
          // fall through
          case 32: break;
          case 6:
            { return UiTypes.RPAREN;
            }
          // fall through
          case 33: break;
          case 7:
            { return UiTypes.COMMA;
            }
          // fall through
          case 34: break;
          case 8:
            { return UiTypes.DOT;
            }
          // fall through
          case 35: break;
          case 9:
            { return UiTypes.NUMBER;
            }
          // fall through
          case 36: break;
          case 10:
            { return UiTypes.COLON;
            }
          // fall through
          case 37: break;
          case 11:
            { return UiTypes.SEMICOLON;
            }
          // fall through
          case 38: break;
          case 12:
            { return UiTypes.EQUALS;
            }
          // fall through
          case 39: break;
          case 13:
            { return UiTypes.AT;
            }
          // fall through
          case 40: break;
          case 14:
            { return UiTypes.IDENTIFIER;
            }
          // fall through
          case 41: break;
          case 15:
            { return UiTypes.LBRACKET;
            }
          // fall through
          case 42: break;
          case 16:
            { return UiTypes.RBRACKET;
            }
          // fall through
          case 43: break;
          case 17:
            { return UiTypes.LBRACE;
            }
          // fall through
          case 44: break;
          case 18:
            { return UiTypes.RBRACE;
            }
          // fall through
          case 45: break;
          case 19:
            { return UiTypes.STRING;
            }
          // fall through
          case 46: break;
          case 20:
            { return UiTypes.COMMENT;
            }
          // fall through
          case 47: break;
          case 21:
            { return UiTypes.SPREAD;
            }
          // fall through
          case 48: break;
          case 22:
            { return UiTypes.PROPERTY;
            }
          // fall through
          case 49: break;
          case 23:
            { return UiTypes.KEYWORD;
            }
          // fall through
          case 50: break;
          case 24:
            { return UiTypes.BOOLEAN;
            }
          // fall through
          case 51: break;
          case 25:
            { return UiTypes.COMPONENT;
            }
          // fall through
          case 52: break;
          case 26:
            { return UiTypes.COLOR;
            }
          // fall through
          case 53: break;
          case 27:
            { return UiTypes.VALUE;
            }
          // fall through
          case 54: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
