// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: src/main/java/org/jetbrains/plugins/template/ui/lexer/Ui.flex

package org.jetbrains.plugins.template.ui.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import org.jetbrains.plugins.template.ui.psi.UiTypes;
import com.intellij.psi.TokenType;


class UiLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\0\1\6\1\7\1\10\3\0\1\11\1\12\1\13"+
    "\1\0\1\14\1\0\1\15\1\16\12\17\1\20\1\21"+
    "\1\0\1\22\2\0\1\23\1\24\1\25\1\26\2\27"+
    "\1\30\1\31\1\32\3\31\1\33\1\34\2\31\1\35"+
    "\1\31\1\36\1\37\1\40\1\31\1\41\1\42\3\31"+
    "\1\0\1\43\2\0\1\31\1\0\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\31\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\31\1\63\1\64"+
    "\1\65\1\66\2\31\1\67\1\70\1\71\1\72\1\0"+
    "\1\73\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\1\12\1\13\1\14\1\15"+
    "\20\16\1\17\1\20\1\0\1\21\4\0\1\22\1\0"+
    "\27\16\1\0\1\23\2\0\1\11\21\16\1\24\5\16"+
    "\2\0\1\22\7\16\1\24\6\16\1\25\3\16\1\26"+
    "\1\0\13\16\1\25\4\16\1\0\14\16\1\27\13\16"+
    "\1\0\11\16\1\0\6\16\1\27\5\16\1\30\4\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\74\0\74\0\74"+
    "\0\74\0\u012c\0\u0168\0\u01a4\0\74\0\74\0\74\0\74"+
    "\0\u01e0\0\u021c\0\u0258\0\u0294\0\u02d0\0\u030c\0\u0348\0\u0384"+
    "\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u0528\0\u0564"+
    "\0\74\0\74\0\264\0\74\0\u05a0\0\u05dc\0\u0618\0\u0654"+
    "\0\u0690\0\u06cc\0\u0708\0\u0744\0\u0780\0\u07bc\0\u07f8\0\u0834"+
    "\0\u0870\0\u08ac\0\u08e8\0\u0924\0\u0960\0\u099c\0\u09d8\0\u0a14"+
    "\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4"+
    "\0\u0c30\0\u0c6c\0\74\0\u0ca8\0\u0ce4\0\u06cc\0\u0d20\0\u0d5c"+
    "\0\u0d98\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88\0\u0ec4\0\u0f00\0\u0f3c"+
    "\0\u0f78\0\u0fb4\0\u0ff0\0\u102c\0\u1068\0\u10a4\0\u10e0\0\u111c"+
    "\0\u1158\0\u1194\0\u11d0\0\u120c\0\u1248\0\u1284\0\u12c0\0\74"+
    "\0\u12fc\0\u1338\0\u1374\0\u13b0\0\u13ec\0\u1428\0\u1464\0\u0294"+
    "\0\u14a0\0\u14dc\0\u1518\0\u1554\0\u1590\0\u15cc\0\u1608\0\u1644"+
    "\0\u1680\0\u16bc\0\u0294\0\u16f8\0\u1734\0\u1770\0\u17ac\0\u17e8"+
    "\0\u1824\0\u1860\0\u189c\0\u18d8\0\u1914\0\u1950\0\u198c\0\u0294"+
    "\0\u19c8\0\u1a04\0\u1a40\0\u1a7c\0\u1ab8\0\u1af4\0\u1b30\0\u1b6c"+
    "\0\u1ba8\0\u1be4\0\u1c20\0\u1c5c\0\u1c98\0\u1cd4\0\u1d10\0\u1d4c"+
    "\0\u1d88\0\u1dc4\0\u1e00\0\u1e3c\0\u1e78\0\u1eb4\0\u1ef0\0\u1f2c"+
    "\0\u1f68\0\u1fa4\0\u1fe0\0\u201c\0\u2058\0\u2094\0\u20d0\0\u210c"+
    "\0\u2148\0\u2184\0\u21c0\0\u21fc\0\u2238\0\u2274\0\u22b0\0\u22ec"+
    "\0\u2328\0\u2364\0\u23a0\0\u23dc\0\u2418\0\u2454\0\74\0\u2490"+
    "\0\u24cc\0\u2508\0\u2544\0\u2580\0\u0294\0\u25bc\0\u25f8\0\u2634"+
    "\0\u2670";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\2\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\24\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\2\5\24\1\37\13\24\1\40\4\24"+
    "\1\41\1\42\75\0\2\3\1\0\1\3\67\0\2\43"+
    "\1\0\2\43\1\0\1\44\34\43\1\45\30\43\17\0"+
    "\1\46\4\0\5\46\13\0\6\46\37\0\1\47\71\0"+
    "\1\50\2\0\1\51\72\0\1\52\1\0\1\14\73\0"+
    "\1\24\4\0\17\24\1\0\14\24\1\53\11\24\21\0"+
    "\1\24\4\0\17\24\1\0\1\54\14\24\1\55\10\24"+
    "\21\0\1\24\4\0\17\24\1\0\4\24\1\56\21\24"+
    "\21\0\1\24\4\0\17\24\1\0\26\24\21\0\1\24"+
    "\4\0\17\24\1\0\12\24\1\57\2\24\1\60\4\24"+
    "\1\61\3\24\21\0\1\24\4\0\17\24\1\0\4\24"+
    "\1\62\21\24\21\0\1\24\4\0\17\24\1\0\1\63"+
    "\3\24\1\64\21\24\21\0\1\24\4\0\17\24\1\0"+
    "\1\65\25\24\21\0\1\24\4\0\17\24\1\0\1\66"+
    "\25\24\21\0\1\24\4\0\17\24\1\0\4\24\1\67"+
    "\3\24\1\70\15\24\21\0\1\24\4\0\17\24\1\0"+
    "\2\24\1\71\16\24\1\72\4\24\21\0\1\24\4\0"+
    "\17\24\1\0\4\24\1\73\10\24\1\74\10\24\21\0"+
    "\1\24\4\0\17\24\1\0\4\24\1\75\21\24\21\0"+
    "\1\24\4\0\17\24\1\0\10\24\1\76\6\24\1\77"+
    "\6\24\21\0\1\24\4\0\17\24\1\0\1\100\25\24"+
    "\21\0\1\24\4\0\17\24\1\0\17\24\1\101\6\24"+
    "\2\0\2\43\4\0\66\43\17\0\1\102\4\0\5\102"+
    "\13\0\6\102\37\0\1\103\56\0\13\104\1\105\60\104"+
    "\2\51\1\0\2\51\1\0\66\51\17\0\1\106\73\0"+
    "\1\24\4\0\17\24\1\0\2\24\1\107\23\24\21\0"+
    "\1\24\4\0\17\24\1\0\2\24\1\110\23\24\21\0"+
    "\1\24\4\0\17\24\1\0\17\24\1\111\1\24\1\112"+
    "\4\24\21\0\1\24\4\0\17\24\1\0\14\24\1\113"+
    "\11\24\21\0\1\24\4\0\17\24\1\0\4\24\1\114"+
    "\21\24\21\0\1\24\4\0\17\24\1\0\14\24\1\115"+
    "\11\24\21\0\1\24\4\0\17\24\1\0\12\24\1\116"+
    "\13\24\21\0\1\24\4\0\17\24\1\0\10\24\1\70"+
    "\15\24\21\0\1\24\4\0\17\24\1\0\24\24\1\117"+
    "\1\24\21\0\1\24\4\0\17\24\1\0\5\24\1\120"+
    "\20\24\21\0\1\24\4\0\17\24\1\0\23\24\1\121"+
    "\2\24\21\0\1\24\4\0\17\24\1\0\3\24\1\122"+
    "\22\24\21\0\1\24\4\0\17\24\1\0\14\24\1\123"+
    "\11\24\21\0\1\24\4\0\17\24\1\0\6\24\1\124"+
    "\17\24\21\0\1\24\4\0\17\24\1\0\17\24\1\125"+
    "\6\24\21\0\1\24\4\0\17\24\1\0\24\24\1\126"+
    "\1\24\21\0\1\24\4\0\17\24\1\0\23\24\1\127"+
    "\2\24\21\0\1\24\4\0\17\24\1\0\16\24\1\130"+
    "\7\24\21\0\1\24\4\0\17\24\1\0\17\24\1\131"+
    "\6\24\21\0\1\24\4\0\17\24\1\0\3\24\1\132"+
    "\22\24\21\0\1\24\4\0\17\24\1\0\1\133\25\24"+
    "\21\0\1\24\4\0\17\24\1\0\12\24\1\134\13\24"+
    "\21\0\1\24\4\0\17\24\1\0\22\24\1\135\3\24"+
    "\21\0\1\136\4\0\5\136\13\0\6\136\22\0\13\104"+
    "\1\137\60\104\13\0\1\105\2\0\1\140\74\0\1\24"+
    "\4\0\17\24\1\0\7\24\1\141\16\24\21\0\1\24"+
    "\4\0\17\24\1\0\11\24\1\142\14\24\21\0\1\24"+
    "\4\0\17\24\1\0\3\24\1\143\22\24\21\0\1\24"+
    "\4\0\17\24\1\0\21\24\1\144\4\24\21\0\1\24"+
    "\4\0\17\24\1\0\21\24\1\145\4\24\21\0\1\24"+
    "\4\0\17\24\1\0\23\24\1\146\2\24\21\0\1\24"+
    "\4\0\17\24\1\0\21\24\1\147\4\24\21\0\1\24"+
    "\4\0\17\24\1\0\12\24\1\150\13\24\21\0\1\24"+
    "\4\0\17\24\1\0\15\24\1\151\10\24\21\0\1\24"+
    "\4\0\17\24\1\0\21\24\1\150\4\24\21\0\1\24"+
    "\4\0\7\24\1\152\7\24\1\0\26\24\21\0\1\24"+
    "\4\0\17\24\1\0\3\24\1\153\22\24\21\0\1\24"+
    "\4\0\17\24\1\0\3\24\1\154\22\24\21\0\1\24"+
    "\4\0\17\24\1\0\7\24\1\120\16\24\21\0\1\24"+
    "\4\0\17\24\1\0\15\24\1\155\10\24\21\0\1\24"+
    "\4\0\17\24\1\0\12\24\1\156\13\24\21\0\1\24"+
    "\4\0\17\24\1\0\21\24\1\157\4\24\21\0\1\24"+
    "\4\0\13\24\1\160\3\24\1\0\26\24\21\0\1\24"+
    "\4\0\17\24\1\0\21\24\1\161\4\24\21\0\1\24"+
    "\4\0\17\24\1\0\21\24\1\162\4\24\21\0\1\24"+
    "\4\0\17\24\1\0\16\24\1\150\7\24\21\0\1\24"+
    "\4\0\17\24\1\0\20\24\1\135\5\24\21\0\1\24"+
    "\4\0\17\24\1\0\4\24\1\163\21\24\21\0\1\164"+
    "\4\0\5\164\13\0\6\164\22\0\13\104\1\137\2\104"+
    "\1\140\55\104\17\0\1\24\4\0\17\24\1\0\15\24"+
    "\1\165\10\24\21\0\1\24\4\0\17\24\1\0\6\24"+
    "\1\166\17\24\21\0\1\24\4\0\17\24\1\0\4\24"+
    "\1\165\21\24\21\0\1\24\4\0\17\24\1\0\15\24"+
    "\1\167\10\24\21\0\1\24\4\0\17\24\1\0\4\24"+
    "\1\170\21\24\21\0\1\24\4\0\16\24\1\171\1\0"+
    "\26\24\21\0\1\24\4\0\13\24\1\172\3\24\1\0"+
    "\26\24\21\0\1\24\4\0\17\24\1\0\22\24\1\173"+
    "\3\24\21\0\1\24\4\0\17\24\1\0\4\24\1\174"+
    "\21\24\21\0\1\24\4\0\17\24\1\0\10\24\1\175"+
    "\15\24\21\0\1\24\4\0\17\24\1\0\4\24\1\176"+
    "\21\24\21\0\1\24\4\0\17\24\1\0\12\24\1\177"+
    "\13\24\21\0\1\24\4\0\17\24\1\0\4\24\1\200"+
    "\21\24\21\0\1\24\4\0\2\24\1\201\14\24\1\0"+
    "\22\24\1\202\3\24\21\0\1\24\4\0\17\24\1\0"+
    "\2\24\1\203\23\24\21\0\1\24\4\0\17\24\1\0"+
    "\10\24\1\204\15\24\21\0\1\24\4\0\17\24\1\0"+
    "\7\24\1\150\16\24\21\0\1\205\4\0\5\205\13\0"+
    "\6\205\41\0\1\24\4\0\17\24\1\0\17\24\1\200"+
    "\6\24\21\0\1\24\4\0\17\24\1\0\17\24\1\206"+
    "\6\24\21\0\1\24\4\0\17\24\1\0\13\24\1\150"+
    "\12\24\21\0\1\24\4\0\17\24\1\0\17\24\1\150"+
    "\6\24\21\0\1\24\4\0\17\24\1\0\4\24\1\207"+
    "\21\24\21\0\1\24\4\0\17\24\1\0\10\24\1\210"+
    "\15\24\21\0\1\24\4\0\17\24\1\0\21\24\1\211"+
    "\4\24\21\0\1\24\4\0\17\24\1\0\14\24\1\212"+
    "\11\24\21\0\1\24\4\0\17\24\1\0\14\24\1\213"+
    "\11\24\21\0\1\24\4\0\17\24\1\0\17\24\1\214"+
    "\6\24\21\0\1\24\4\0\17\24\1\0\12\24\1\215"+
    "\13\24\21\0\1\24\4\0\17\24\1\0\15\24\1\216"+
    "\10\24\21\0\1\24\4\0\17\24\1\0\17\24\1\217"+
    "\6\24\21\0\1\24\4\0\17\24\1\0\17\24\1\220"+
    "\6\24\21\0\1\24\4\0\17\24\1\0\2\24\1\221"+
    "\23\24\21\0\1\222\4\0\5\222\13\0\6\222\41\0"+
    "\1\24\4\0\17\24\1\0\15\24\1\223\10\24\21\0"+
    "\1\24\4\0\17\24\1\0\10\24\1\224\15\24\21\0"+
    "\1\24\4\0\17\24\1\0\25\24\1\225\21\0\1\24"+
    "\4\0\10\24\1\226\6\24\1\0\26\24\21\0\1\24"+
    "\4\0\17\24\1\0\6\24\1\227\17\24\21\0\1\24"+
    "\4\0\17\24\1\0\6\24\1\200\17\24\21\0\1\24"+
    "\4\0\1\24\1\230\15\24\1\0\26\24\21\0\1\24"+
    "\4\0\17\24\1\0\1\24\1\231\24\24\21\0\1\24"+
    "\4\0\17\24\1\0\12\24\1\232\13\24\21\0\1\24"+
    "\4\0\17\24\1\0\4\24\1\233\21\24\21\0\1\24"+
    "\4\0\17\24\1\0\15\24\1\234\10\24\21\0\1\24"+
    "\4\0\17\24\1\0\1\235\25\24\13\0\1\236\101\0"+
    "\1\24\4\0\17\24\1\0\22\24\1\237\3\24\21\0"+
    "\1\24\4\0\17\24\1\0\6\24\1\240\17\24\21\0"+
    "\1\24\4\0\17\24\1\0\4\24\1\150\21\24\21\0"+
    "\1\24\4\0\17\24\1\0\15\24\1\241\10\24\21\0"+
    "\1\24\4\0\17\24\1\0\21\24\1\242\4\24\21\0"+
    "\1\24\4\0\17\24\1\0\15\24\1\243\10\24\21\0"+
    "\1\24\4\0\17\24\1\0\1\244\25\24\21\0\1\24"+
    "\4\0\17\24\1\0\15\24\1\170\10\24\21\0\1\24"+
    "\4\0\11\24\1\245\5\24\1\0\26\24\21\0\1\24"+
    "\4\0\17\24\1\0\12\24\1\246\13\24\21\0\1\24"+
    "\4\0\17\24\1\0\12\24\1\247\13\24\17\0\1\250"+
    "\1\0\1\250\73\0\1\24\4\0\17\24\1\0\14\24"+
    "\1\251\11\24\21\0\1\24\4\0\17\24\1\0\7\24"+
    "\1\252\16\24\21\0\1\24\4\0\17\24\1\0\3\24"+
    "\1\156\22\24\21\0\1\24\4\0\17\24\1\0\7\24"+
    "\1\200\16\24\21\0\1\24\4\0\17\24\1\0\12\24"+
    "\1\253\13\24\21\0\1\24\4\0\17\24\1\0\17\24"+
    "\1\254\6\24\21\0\1\24\4\0\17\24\1\0\1\227"+
    "\25\24\21\0\1\24\4\0\17\24\1\0\12\24\1\255"+
    "\13\24\21\0\1\24\4\0\1\256\16\24\1\0\26\24"+
    "\14\0\1\257\2\0\1\250\1\0\1\250\73\0\1\24"+
    "\4\0\17\24\1\0\3\24\1\200\22\24\21\0\1\24"+
    "\4\0\17\24\1\0\21\24\1\200\4\24\21\0\1\24"+
    "\4\0\17\24\1\0\3\24\1\150\22\24\21\0\1\24"+
    "\4\0\13\24\1\260\3\24\1\0\26\24\21\0\1\24"+
    "\4\0\17\24\1\0\10\24\1\261\15\24\21\0\1\24"+
    "\4\0\17\24\1\0\12\24\1\262\13\24\21\0\1\24"+
    "\4\0\17\24\1\0\21\24\1\72\4\24\21\0\1\24"+
    "\4\0\17\24\1\0\14\24\1\263\11\24\21\0\1\24"+
    "\4\0\17\24\1\0\10\24\1\264\15\24\21\0\1\24"+
    "\4\0\17\24\1\0\6\24\1\265\17\24\21\0\1\24"+
    "\4\0\17\24\1\0\6\24\1\266\17\24\21\0\1\24"+
    "\4\0\17\24\1\0\14\24\1\267\11\24\21\0\1\24"+
    "\4\0\17\24\1\0\13\24\1\270\12\24\21\0\1\24"+
    "\4\0\17\24\1\0\4\24\1\271\21\24\21\0\1\24"+
    "\4\0\17\24\1\0\14\24\1\120\11\24\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9900];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\4\11\3\1\4\11\20\1\2\11"+
    "\1\0\1\11\4\0\1\1\1\0\27\1\1\0\1\11"+
    "\2\0\30\1\2\0\1\11\23\1\1\0\20\1\1\0"+
    "\30\1\1\0\11\1\1\0\6\1\1\11\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  UiLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return TokenType.BAD_CHARACTER;
            }
          // fall through
          case 25: break;
          case 2:
            { return TokenType.WHITE_SPACE;
            }
          // fall through
          case 26: break;
          case 3:
            { return UiTypes.HASH;
            }
          // fall through
          case 27: break;
          case 4:
            { return UiTypes.DOLLAR;
            }
          // fall through
          case 28: break;
          case 5:
            { return UiTypes.LPAREN;
            }
          // fall through
          case 29: break;
          case 6:
            { return UiTypes.RPAREN;
            }
          // fall through
          case 30: break;
          case 7:
            { return UiTypes.COMMA;
            }
          // fall through
          case 31: break;
          case 8:
            { return UiTypes.DOT;
            }
          // fall through
          case 32: break;
          case 9:
            { return UiTypes.NUMBER;
            }
          // fall through
          case 33: break;
          case 10:
            { return UiTypes.COLON;
            }
          // fall through
          case 34: break;
          case 11:
            { return UiTypes.SEMICOLON;
            }
          // fall through
          case 35: break;
          case 12:
            { return UiTypes.EQUALS;
            }
          // fall through
          case 36: break;
          case 13:
            { return UiTypes.AT;
            }
          // fall through
          case 37: break;
          case 14:
            { return UiTypes.IDENTIFIER;
            }
          // fall through
          case 38: break;
          case 15:
            { return UiTypes.LBRACE;
            }
          // fall through
          case 39: break;
          case 16:
            { return UiTypes.RBRACE;
            }
          // fall through
          case 40: break;
          case 17:
            { return UiTypes.STRING;
            }
          // fall through
          case 41: break;
          case 18:
            { return UiTypes.COMMENT;
            }
          // fall through
          case 42: break;
          case 19:
            { return UiTypes.SPREAD;
            }
          // fall through
          case 43: break;
          case 20:
            { return UiTypes.PROPERTY;
            }
          // fall through
          case 44: break;
          case 21:
            { return UiTypes.KEYWORD;
            }
          // fall through
          case 45: break;
          case 22:
            { return UiTypes.BOOLEAN;
            }
          // fall through
          case 46: break;
          case 23:
            { return UiTypes.COLOR;
            }
          // fall through
          case 47: break;
          case 24:
            { return UiTypes.VALUE;
            }
          // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
