// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: src/main/java/org/jetbrains/plugins/template/ui/lexer/Ui.flex

package org.jetbrains.plugins.template.ui.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import org.jetbrains.plugins.template.ui.psi.UiTypes;
import com.intellij.psi.TokenType;


class UiLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\0\1\6\1\7\1\10\3\0\1\11\1\12\1\13"+
    "\1\0\1\14\1\0\1\15\1\16\12\17\1\20\1\21"+
    "\1\0\1\22\2\0\1\23\1\24\1\25\1\26\2\27"+
    "\1\30\1\31\1\32\3\31\1\33\1\34\2\31\1\35"+
    "\1\31\1\36\1\37\1\40\1\31\1\41\1\42\3\31"+
    "\1\43\1\44\1\45\1\0\1\31\1\0\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\31"+
    "\1\57\1\60\1\61\1\62\1\63\1\64\1\31\1\65"+
    "\1\66\1\67\1\70\2\31\1\71\1\72\1\73\1\74"+
    "\1\0\1\75\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\1\12\1\13\1\14\1\15"+
    "\16\16\1\17\1\20\2\16\1\21\1\22\1\0\1\23"+
    "\4\0\1\24\1\0\27\16\1\0\1\25\2\0\1\11"+
    "\21\16\1\26\5\16\2\0\1\24\7\16\1\26\6\16"+
    "\1\27\3\16\1\30\1\0\13\16\1\27\4\16\1\0"+
    "\14\16\1\31\13\16\1\0\11\16\1\0\6\16\1\31"+
    "\5\16\1\32\4\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\76\0\76\0\76"+
    "\0\76\0\u0136\0\u0174\0\u01b2\0\76\0\76\0\76\0\76"+
    "\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\u0364\0\u03a2"+
    "\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516\0\76\0\76"+
    "\0\u0554\0\u0592\0\76\0\76\0\272\0\76\0\u05d0\0\u060e"+
    "\0\u064c\0\u068a\0\u06c8\0\u0706\0\u0744\0\u0782\0\u07c0\0\u07fe"+
    "\0\u083c\0\u087a\0\u08b8\0\u08f6\0\u0934\0\u0972\0\u09b0\0\u09ee"+
    "\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0\0\u0bde"+
    "\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6\0\76\0\u0d14\0\u0d52\0\u0706"+
    "\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a\0\u0e88\0\u0ec6\0\u0f04\0\u0f42"+
    "\0\u0f80\0\u0fbe\0\u0ffc\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132"+
    "\0\u1170\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322"+
    "\0\u1360\0\76\0\u139e\0\u13dc\0\u141a\0\u1458\0\u1496\0\u14d4"+
    "\0\u1512\0\u02aa\0\u1550\0\u158e\0\u15cc\0\u160a\0\u1648\0\u1686"+
    "\0\u16c4\0\u1702\0\u1740\0\u177e\0\u02aa\0\u17bc\0\u17fa\0\u1838"+
    "\0\u1876\0\u18b4\0\u18f2\0\u1930\0\u196e\0\u19ac\0\u19ea\0\u1a28"+
    "\0\u1a66\0\u02aa\0\u1aa4\0\u1ae2\0\u1b20\0\u1b5e\0\u1b9c\0\u1bda"+
    "\0\u1c18\0\u1c56\0\u1c94\0\u1cd2\0\u1d10\0\u1d4e\0\u1d8c\0\u1dca"+
    "\0\u1e08\0\u1e46\0\u1e84\0\u1ec2\0\u1f00\0\u1f3e\0\u1f7c\0\u1fba"+
    "\0\u1ff8\0\u2036\0\u2074\0\u20b2\0\u20f0\0\u212e\0\u216c\0\u21aa"+
    "\0\u21e8\0\u2226\0\u2264\0\u22a2\0\u22e0\0\u231e\0\u235c\0\u239a"+
    "\0\u23d8\0\u2416\0\u2454\0\u2492\0\u24d0\0\u250e\0\u254c\0\u258a"+
    "\0\76\0\u25c8\0\u2606\0\u2644\0\u2682\0\u26c0\0\u02aa\0\u26fe"+
    "\0\u273c\0\u277a\0\u27b8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\2\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\24\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\2\1\40\5\24\1\41\13\24"+
    "\1\42\4\24\1\43\1\44\77\0\2\3\1\0\1\3"+
    "\71\0\2\45\1\0\2\45\1\0\1\46\35\45\1\47"+
    "\31\45\17\0\1\50\4\0\5\50\15\0\6\50\37\0"+
    "\1\51\73\0\1\52\2\0\1\53\74\0\1\54\1\0"+
    "\1\14\75\0\1\24\4\0\17\24\3\0\14\24\1\55"+
    "\11\24\21\0\1\24\4\0\17\24\3\0\1\56\14\24"+
    "\1\57\10\24\21\0\1\24\4\0\17\24\3\0\4\24"+
    "\1\60\21\24\21\0\1\24\4\0\17\24\3\0\26\24"+
    "\21\0\1\24\4\0\17\24\3\0\12\24\1\61\2\24"+
    "\1\62\4\24\1\63\3\24\21\0\1\24\4\0\17\24"+
    "\3\0\4\24\1\64\21\24\21\0\1\24\4\0\17\24"+
    "\3\0\1\65\3\24\1\66\21\24\21\0\1\24\4\0"+
    "\17\24\3\0\1\67\25\24\21\0\1\24\4\0\17\24"+
    "\3\0\1\70\25\24\21\0\1\24\4\0\17\24\3\0"+
    "\4\24\1\71\3\24\1\72\15\24\21\0\1\24\4\0"+
    "\17\24\3\0\2\24\1\73\16\24\1\74\4\24\21\0"+
    "\1\24\4\0\17\24\3\0\4\24\1\75\10\24\1\76"+
    "\10\24\21\0\1\24\4\0\17\24\3\0\4\24\1\77"+
    "\21\24\21\0\1\24\4\0\17\24\3\0\10\24\1\100"+
    "\6\24\1\101\6\24\21\0\1\24\4\0\17\24\3\0"+
    "\1\102\25\24\21\0\1\24\4\0\17\24\3\0\17\24"+
    "\1\103\6\24\2\0\2\45\4\0\70\45\17\0\1\104"+
    "\4\0\5\104\15\0\6\104\37\0\1\105\60\0\13\106"+
    "\1\107\62\106\2\53\1\0\2\53\1\0\70\53\17\0"+
    "\1\110\75\0\1\24\4\0\17\24\3\0\2\24\1\111"+
    "\23\24\21\0\1\24\4\0\17\24\3\0\2\24\1\112"+
    "\23\24\21\0\1\24\4\0\17\24\3\0\17\24\1\113"+
    "\1\24\1\114\4\24\21\0\1\24\4\0\17\24\3\0"+
    "\14\24\1\115\11\24\21\0\1\24\4\0\17\24\3\0"+
    "\4\24\1\116\21\24\21\0\1\24\4\0\17\24\3\0"+
    "\14\24\1\117\11\24\21\0\1\24\4\0\17\24\3\0"+
    "\12\24\1\120\13\24\21\0\1\24\4\0\17\24\3\0"+
    "\10\24\1\72\15\24\21\0\1\24\4\0\17\24\3\0"+
    "\24\24\1\121\1\24\21\0\1\24\4\0\17\24\3\0"+
    "\5\24\1\122\20\24\21\0\1\24\4\0\17\24\3\0"+
    "\23\24\1\123\2\24\21\0\1\24\4\0\17\24\3\0"+
    "\3\24\1\124\22\24\21\0\1\24\4\0\17\24\3\0"+
    "\14\24\1\125\11\24\21\0\1\24\4\0\17\24\3\0"+
    "\6\24\1\126\17\24\21\0\1\24\4\0\17\24\3\0"+
    "\17\24\1\127\6\24\21\0\1\24\4\0\17\24\3\0"+
    "\24\24\1\130\1\24\21\0\1\24\4\0\17\24\3\0"+
    "\23\24\1\131\2\24\21\0\1\24\4\0\17\24\3\0"+
    "\16\24\1\132\7\24\21\0\1\24\4\0\17\24\3\0"+
    "\17\24\1\133\6\24\21\0\1\24\4\0\17\24\3\0"+
    "\3\24\1\134\22\24\21\0\1\24\4\0\17\24\3\0"+
    "\1\135\25\24\21\0\1\24\4\0\17\24\3\0\12\24"+
    "\1\136\13\24\21\0\1\24\4\0\17\24\3\0\22\24"+
    "\1\137\3\24\21\0\1\140\4\0\5\140\15\0\6\140"+
    "\22\0\13\106\1\141\62\106\13\0\1\107\2\0\1\142"+
    "\76\0\1\24\4\0\17\24\3\0\7\24\1\143\16\24"+
    "\21\0\1\24\4\0\17\24\3\0\11\24\1\144\14\24"+
    "\21\0\1\24\4\0\17\24\3\0\3\24\1\145\22\24"+
    "\21\0\1\24\4\0\17\24\3\0\21\24\1\146\4\24"+
    "\21\0\1\24\4\0\17\24\3\0\21\24\1\147\4\24"+
    "\21\0\1\24\4\0\17\24\3\0\23\24\1\150\2\24"+
    "\21\0\1\24\4\0\17\24\3\0\21\24\1\151\4\24"+
    "\21\0\1\24\4\0\17\24\3\0\12\24\1\152\13\24"+
    "\21\0\1\24\4\0\17\24\3\0\15\24\1\153\10\24"+
    "\21\0\1\24\4\0\17\24\3\0\21\24\1\152\4\24"+
    "\21\0\1\24\4\0\7\24\1\154\7\24\3\0\26\24"+
    "\21\0\1\24\4\0\17\24\3\0\3\24\1\155\22\24"+
    "\21\0\1\24\4\0\17\24\3\0\3\24\1\156\22\24"+
    "\21\0\1\24\4\0\17\24\3\0\7\24\1\122\16\24"+
    "\21\0\1\24\4\0\17\24\3\0\15\24\1\157\10\24"+
    "\21\0\1\24\4\0\17\24\3\0\12\24\1\160\13\24"+
    "\21\0\1\24\4\0\17\24\3\0\21\24\1\161\4\24"+
    "\21\0\1\24\4\0\13\24\1\162\3\24\3\0\26\24"+
    "\21\0\1\24\4\0\17\24\3\0\21\24\1\163\4\24"+
    "\21\0\1\24\4\0\17\24\3\0\21\24\1\164\4\24"+
    "\21\0\1\24\4\0\17\24\3\0\16\24\1\152\7\24"+
    "\21\0\1\24\4\0\17\24\3\0\20\24\1\137\5\24"+
    "\21\0\1\24\4\0\17\24\3\0\4\24\1\165\21\24"+
    "\21\0\1\166\4\0\5\166\15\0\6\166\22\0\13\106"+
    "\1\141\2\106\1\142\57\106\17\0\1\24\4\0\17\24"+
    "\3\0\15\24\1\167\10\24\21\0\1\24\4\0\17\24"+
    "\3\0\6\24\1\170\17\24\21\0\1\24\4\0\17\24"+
    "\3\0\4\24\1\167\21\24\21\0\1\24\4\0\17\24"+
    "\3\0\15\24\1\171\10\24\21\0\1\24\4\0\17\24"+
    "\3\0\4\24\1\172\21\24\21\0\1\24\4\0\16\24"+
    "\1\173\3\0\26\24\21\0\1\24\4\0\13\24\1\174"+
    "\3\24\3\0\26\24\21\0\1\24\4\0\17\24\3\0"+
    "\22\24\1\175\3\24\21\0\1\24\4\0\17\24\3\0"+
    "\4\24\1\176\21\24\21\0\1\24\4\0\17\24\3\0"+
    "\10\24\1\177\15\24\21\0\1\24\4\0\17\24\3\0"+
    "\4\24\1\200\21\24\21\0\1\24\4\0\17\24\3\0"+
    "\12\24\1\201\13\24\21\0\1\24\4\0\17\24\3\0"+
    "\4\24\1\202\21\24\21\0\1\24\4\0\2\24\1\203"+
    "\14\24\3\0\22\24\1\204\3\24\21\0\1\24\4\0"+
    "\17\24\3\0\2\24\1\205\23\24\21\0\1\24\4\0"+
    "\17\24\3\0\10\24\1\206\15\24\21\0\1\24\4\0"+
    "\17\24\3\0\7\24\1\152\16\24\21\0\1\207\4\0"+
    "\5\207\15\0\6\207\41\0\1\24\4\0\17\24\3\0"+
    "\17\24\1\202\6\24\21\0\1\24\4\0\17\24\3\0"+
    "\17\24\1\210\6\24\21\0\1\24\4\0\17\24\3\0"+
    "\13\24\1\152\12\24\21\0\1\24\4\0\17\24\3\0"+
    "\17\24\1\152\6\24\21\0\1\24\4\0\17\24\3\0"+
    "\4\24\1\211\21\24\21\0\1\24\4\0\17\24\3\0"+
    "\10\24\1\212\15\24\21\0\1\24\4\0\17\24\3\0"+
    "\21\24\1\213\4\24\21\0\1\24\4\0\17\24\3\0"+
    "\14\24\1\214\11\24\21\0\1\24\4\0\17\24\3\0"+
    "\14\24\1\215\11\24\21\0\1\24\4\0\17\24\3\0"+
    "\17\24\1\216\6\24\21\0\1\24\4\0\17\24\3\0"+
    "\12\24\1\217\13\24\21\0\1\24\4\0\17\24\3\0"+
    "\15\24\1\220\10\24\21\0\1\24\4\0\17\24\3\0"+
    "\17\24\1\221\6\24\21\0\1\24\4\0\17\24\3\0"+
    "\17\24\1\222\6\24\21\0\1\24\4\0\17\24\3\0"+
    "\2\24\1\223\23\24\21\0\1\224\4\0\5\224\15\0"+
    "\6\224\41\0\1\24\4\0\17\24\3\0\15\24\1\225"+
    "\10\24\21\0\1\24\4\0\17\24\3\0\10\24\1\226"+
    "\15\24\21\0\1\24\4\0\17\24\3\0\25\24\1\227"+
    "\21\0\1\24\4\0\10\24\1\230\6\24\3\0\26\24"+
    "\21\0\1\24\4\0\17\24\3\0\6\24\1\231\17\24"+
    "\21\0\1\24\4\0\17\24\3\0\6\24\1\202\17\24"+
    "\21\0\1\24\4\0\1\24\1\232\15\24\3\0\26\24"+
    "\21\0\1\24\4\0\17\24\3\0\1\24\1\233\24\24"+
    "\21\0\1\24\4\0\17\24\3\0\12\24\1\234\13\24"+
    "\21\0\1\24\4\0\17\24\3\0\4\24\1\235\21\24"+
    "\21\0\1\24\4\0\17\24\3\0\15\24\1\236\10\24"+
    "\21\0\1\24\4\0\17\24\3\0\1\237\25\24\13\0"+
    "\1\240\103\0\1\24\4\0\17\24\3\0\22\24\1\241"+
    "\3\24\21\0\1\24\4\0\17\24\3\0\6\24\1\242"+
    "\17\24\21\0\1\24\4\0\17\24\3\0\4\24\1\152"+
    "\21\24\21\0\1\24\4\0\17\24\3\0\15\24\1\243"+
    "\10\24\21\0\1\24\4\0\17\24\3\0\21\24\1\244"+
    "\4\24\21\0\1\24\4\0\17\24\3\0\15\24\1\245"+
    "\10\24\21\0\1\24\4\0\17\24\3\0\1\246\25\24"+
    "\21\0\1\24\4\0\17\24\3\0\15\24\1\172\10\24"+
    "\21\0\1\24\4\0\11\24\1\247\5\24\3\0\26\24"+
    "\21\0\1\24\4\0\17\24\3\0\12\24\1\250\13\24"+
    "\21\0\1\24\4\0\17\24\3\0\12\24\1\251\13\24"+
    "\17\0\1\252\1\0\1\252\75\0\1\24\4\0\17\24"+
    "\3\0\14\24\1\253\11\24\21\0\1\24\4\0\17\24"+
    "\3\0\7\24\1\254\16\24\21\0\1\24\4\0\17\24"+
    "\3\0\3\24\1\160\22\24\21\0\1\24\4\0\17\24"+
    "\3\0\7\24\1\202\16\24\21\0\1\24\4\0\17\24"+
    "\3\0\12\24\1\255\13\24\21\0\1\24\4\0\17\24"+
    "\3\0\17\24\1\256\6\24\21\0\1\24\4\0\17\24"+
    "\3\0\1\231\25\24\21\0\1\24\4\0\17\24\3\0"+
    "\12\24\1\257\13\24\21\0\1\24\4\0\1\260\16\24"+
    "\3\0\26\24\14\0\1\261\2\0\1\252\1\0\1\252"+
    "\75\0\1\24\4\0\17\24\3\0\3\24\1\202\22\24"+
    "\21\0\1\24\4\0\17\24\3\0\21\24\1\202\4\24"+
    "\21\0\1\24\4\0\17\24\3\0\3\24\1\152\22\24"+
    "\21\0\1\24\4\0\13\24\1\262\3\24\3\0\26\24"+
    "\21\0\1\24\4\0\17\24\3\0\10\24\1\263\15\24"+
    "\21\0\1\24\4\0\17\24\3\0\12\24\1\264\13\24"+
    "\21\0\1\24\4\0\17\24\3\0\21\24\1\74\4\24"+
    "\21\0\1\24\4\0\17\24\3\0\14\24\1\265\11\24"+
    "\21\0\1\24\4\0\17\24\3\0\10\24\1\266\15\24"+
    "\21\0\1\24\4\0\17\24\3\0\6\24\1\267\17\24"+
    "\21\0\1\24\4\0\17\24\3\0\6\24\1\270\17\24"+
    "\21\0\1\24\4\0\17\24\3\0\14\24\1\271\11\24"+
    "\21\0\1\24\4\0\17\24\3\0\13\24\1\272\12\24"+
    "\21\0\1\24\4\0\17\24\3\0\4\24\1\273\21\24"+
    "\21\0\1\24\4\0\17\24\3\0\14\24\1\122\11\24"+
    "\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10230];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\4\11\3\1\4\11\16\1\2\11"+
    "\2\1\2\11\1\0\1\11\4\0\1\1\1\0\27\1"+
    "\1\0\1\11\2\0\30\1\2\0\1\11\23\1\1\0"+
    "\20\1\1\0\30\1\1\0\11\1\1\0\6\1\1\11"+
    "\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[187];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  UiLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return TokenType.BAD_CHARACTER;
            }
          // fall through
          case 27: break;
          case 2:
            { return TokenType.WHITE_SPACE;
            }
          // fall through
          case 28: break;
          case 3:
            { return UiTypes.HASH;
            }
          // fall through
          case 29: break;
          case 4:
            { return UiTypes.DOLLAR;
            }
          // fall through
          case 30: break;
          case 5:
            { return UiTypes.LPAREN;
            }
          // fall through
          case 31: break;
          case 6:
            { return UiTypes.RPAREN;
            }
          // fall through
          case 32: break;
          case 7:
            { return UiTypes.COMMA;
            }
          // fall through
          case 33: break;
          case 8:
            { return UiTypes.DOT;
            }
          // fall through
          case 34: break;
          case 9:
            { return UiTypes.NUMBER;
            }
          // fall through
          case 35: break;
          case 10:
            { return UiTypes.COLON;
            }
          // fall through
          case 36: break;
          case 11:
            { return UiTypes.SEMICOLON;
            }
          // fall through
          case 37: break;
          case 12:
            { return UiTypes.EQUALS;
            }
          // fall through
          case 38: break;
          case 13:
            { return UiTypes.AT;
            }
          // fall through
          case 39: break;
          case 14:
            { return UiTypes.IDENTIFIER;
            }
          // fall through
          case 40: break;
          case 15:
            { return UiTypes.LBRACKET;
            }
          // fall through
          case 41: break;
          case 16:
            { return UiTypes.RBRACKET;
            }
          // fall through
          case 42: break;
          case 17:
            { return UiTypes.LBRACE;
            }
          // fall through
          case 43: break;
          case 18:
            { return UiTypes.RBRACE;
            }
          // fall through
          case 44: break;
          case 19:
            { return UiTypes.STRING;
            }
          // fall through
          case 45: break;
          case 20:
            { return UiTypes.COMMENT;
            }
          // fall through
          case 46: break;
          case 21:
            { return UiTypes.SPREAD;
            }
          // fall through
          case 47: break;
          case 22:
            { return UiTypes.PROPERTY;
            }
          // fall through
          case 48: break;
          case 23:
            { return UiTypes.KEYWORD;
            }
          // fall through
          case 49: break;
          case 24:
            { return UiTypes.BOOLEAN;
            }
          // fall through
          case 50: break;
          case 25:
            { return UiTypes.COLOR;
            }
          // fall through
          case 51: break;
          case 26:
            { return UiTypes.VALUE;
            }
          // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
